apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-03-02T21:39:04Z"
  generation: 1
  labels:
    app: proxy
  name: proxy
  namespace: default
  resourceVersion: "2623"
  uid: d89112da-8b4f-4bc4-8d34-31c9c607a447
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: proxy
  strategy:
    rollingUpdate:
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: proxy
    spec:
      containers:
      - image: nginx:1.9
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

