apiVersion: v1
kind: Pod
metadata:
  name: lab10-pod
spec:
  containers:
  - name: httpd
    image: httpd
    volumeMounts:
      - mountPath: "/var/local/aaa"
        name: lab10
  volumes:
    - name: lab10
      persistentVolumeClaim: 
        claimName: lab10-pvc

