apiVersion: batch/v1
kind: CronJob
metadata: 
  name: sleep-job
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command:
            - sleep
            - "300"
